/*
Qovery API

Testing HelmDeploymentRestrictionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package qovery

import (
	"context"
	openapiclient "github.com/qovery/qovery-client-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_qovery_HelmDeploymentRestrictionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HelmDeploymentRestrictionAPIService CreateHelmDeploymentRestriction", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var helmId string

		resp, httpRes, err := apiClient.HelmDeploymentRestrictionAPI.CreateHelmDeploymentRestriction(context.Background(), helmId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HelmDeploymentRestrictionAPIService DeleteHelmDeploymentRestriction", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var helmId string
		var deploymentRestrictionId string

		httpRes, err := apiClient.HelmDeploymentRestrictionAPI.DeleteHelmDeploymentRestriction(context.Background(), helmId, deploymentRestrictionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HelmDeploymentRestrictionAPIService EditHelmDeploymentRestriction", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var helmId string
		var deploymentRestrictionId string

		resp, httpRes, err := apiClient.HelmDeploymentRestrictionAPI.EditHelmDeploymentRestriction(context.Background(), helmId, deploymentRestrictionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HelmDeploymentRestrictionAPIService GetHelmDeploymentRestrictions", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var helmId string

		resp, httpRes, err := apiClient.HelmDeploymentRestrictionAPI.GetHelmDeploymentRestrictions(context.Background(), helmId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
