/*
Qovery API

Testing TerraformConfigurationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package qovery

import (
	"context"
	openapiclient "github.com/qovery/qovery-client-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_qovery_TerraformConfigurationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TerraformConfigurationAPIService EditTerraformAdvancedSettings", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var terraformId string

		resp, httpRes, err := apiClient.TerraformConfigurationAPI.EditTerraformAdvancedSettings(context.Background(), terraformId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TerraformConfigurationAPIService GetTerraformAdvancedSettings", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var terraformId string

		resp, httpRes, err := apiClient.TerraformConfigurationAPI.GetTerraformAdvancedSettings(context.Background(), terraformId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
