/*
Qovery API

Testing DatabaseMainCallsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package qovery

import (
	"context"
	openapiclient "github.com/qovery/qovery-client-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_qovery_DatabaseMainCallsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DatabaseMainCallsAPIService DeleteDatabase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var databaseId string

		httpRes, err := apiClient.DatabaseMainCallsAPI.DeleteDatabase(context.Background(), databaseId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabaseMainCallsAPIService EditDatabase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var databaseId string

		resp, httpRes, err := apiClient.DatabaseMainCallsAPI.EditDatabase(context.Background(), databaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabaseMainCallsAPIService EditDatabaseCredentials", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var databaseId string

		resp, httpRes, err := apiClient.DatabaseMainCallsAPI.EditDatabaseCredentials(context.Background(), databaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabaseMainCallsAPIService GetDatabase", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var databaseId string

		resp, httpRes, err := apiClient.DatabaseMainCallsAPI.GetDatabase(context.Background(), databaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabaseMainCallsAPIService GetDatabaseMasterCredentials", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var databaseId string

		resp, httpRes, err := apiClient.DatabaseMainCallsAPI.GetDatabaseMasterCredentials(context.Background(), databaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabaseMainCallsAPIService GetDatabaseStatus", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var databaseId string

		resp, httpRes, err := apiClient.DatabaseMainCallsAPI.GetDatabaseStatus(context.Background(), databaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabaseMainCallsAPIService ListDatabaseVersion", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var databaseId string

		resp, httpRes, err := apiClient.DatabaseMainCallsAPI.ListDatabaseVersion(context.Background(), databaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
