/*
Qovery API

- Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.

API version: 1.0.3
Contact: support+api+documentation@qovery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery

import (
	"encoding/json"
)

// EnvironmentVariableEditRequest struct for EnvironmentVariableEditRequest
type EnvironmentVariableEditRequest struct {
	// key is case sensitive
	Key string `json:"key"`
	// value of the env variable.
	Value *string `json:"value,omitempty"`
}

// NewEnvironmentVariableEditRequest instantiates a new EnvironmentVariableEditRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentVariableEditRequest(key string) *EnvironmentVariableEditRequest {
	this := EnvironmentVariableEditRequest{}
	this.Key = key
	return &this
}

// NewEnvironmentVariableEditRequestWithDefaults instantiates a new EnvironmentVariableEditRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentVariableEditRequestWithDefaults() *EnvironmentVariableEditRequest {
	this := EnvironmentVariableEditRequest{}
	return &this
}

// GetKey returns the Key field value
func (o *EnvironmentVariableEditRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *EnvironmentVariableEditRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *EnvironmentVariableEditRequest) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *EnvironmentVariableEditRequest) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentVariableEditRequest) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *EnvironmentVariableEditRequest) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *EnvironmentVariableEditRequest) SetValue(v string) {
	o.Value = &v
}

func (o EnvironmentVariableEditRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["key"] = o.Key
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableEnvironmentVariableEditRequest struct {
	value *EnvironmentVariableEditRequest
	isSet bool
}

func (v NullableEnvironmentVariableEditRequest) Get() *EnvironmentVariableEditRequest {
	return v.value
}

func (v *NullableEnvironmentVariableEditRequest) Set(val *EnvironmentVariableEditRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentVariableEditRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentVariableEditRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentVariableEditRequest(val *EnvironmentVariableEditRequest) *NullableEnvironmentVariableEditRequest {
	return &NullableEnvironmentVariableEditRequest{value: val, isSet: true}
}

func (v NullableEnvironmentVariableEditRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentVariableEditRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
