/*
Qovery API

- Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.

API version: 1.0.3
Contact: support+api+documentation@qovery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HelmResponseAllOfValuesOverrideFileRawValues type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelmResponseAllOfValuesOverrideFileRawValues{}

// HelmResponseAllOfValuesOverrideFileRawValues struct for HelmResponseAllOfValuesOverrideFileRawValues
type HelmResponseAllOfValuesOverrideFileRawValues struct {
	// The name of the value file
	Name string `json:"name"`
	// The content of the value file
	Content string `json:"content"`
}

type _HelmResponseAllOfValuesOverrideFileRawValues HelmResponseAllOfValuesOverrideFileRawValues

// NewHelmResponseAllOfValuesOverrideFileRawValues instantiates a new HelmResponseAllOfValuesOverrideFileRawValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelmResponseAllOfValuesOverrideFileRawValues(name string, content string) *HelmResponseAllOfValuesOverrideFileRawValues {
	this := HelmResponseAllOfValuesOverrideFileRawValues{}
	this.Name = name
	this.Content = content
	return &this
}

// NewHelmResponseAllOfValuesOverrideFileRawValuesWithDefaults instantiates a new HelmResponseAllOfValuesOverrideFileRawValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelmResponseAllOfValuesOverrideFileRawValuesWithDefaults() *HelmResponseAllOfValuesOverrideFileRawValues {
	this := HelmResponseAllOfValuesOverrideFileRawValues{}
	return &this
}

// GetName returns the Name field value
func (o *HelmResponseAllOfValuesOverrideFileRawValues) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HelmResponseAllOfValuesOverrideFileRawValues) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HelmResponseAllOfValuesOverrideFileRawValues) SetName(v string) {
	o.Name = v
}

// GetContent returns the Content field value
func (o *HelmResponseAllOfValuesOverrideFileRawValues) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *HelmResponseAllOfValuesOverrideFileRawValues) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *HelmResponseAllOfValuesOverrideFileRawValues) SetContent(v string) {
	o.Content = v
}

func (o HelmResponseAllOfValuesOverrideFileRawValues) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelmResponseAllOfValuesOverrideFileRawValues) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *HelmResponseAllOfValuesOverrideFileRawValues) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelmResponseAllOfValuesOverrideFileRawValues := _HelmResponseAllOfValuesOverrideFileRawValues{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHelmResponseAllOfValuesOverrideFileRawValues)

	if err != nil {
		return err
	}

	*o = HelmResponseAllOfValuesOverrideFileRawValues(varHelmResponseAllOfValuesOverrideFileRawValues)

	return err
}

type NullableHelmResponseAllOfValuesOverrideFileRawValues struct {
	value *HelmResponseAllOfValuesOverrideFileRawValues
	isSet bool
}

func (v NullableHelmResponseAllOfValuesOverrideFileRawValues) Get() *HelmResponseAllOfValuesOverrideFileRawValues {
	return v.value
}

func (v *NullableHelmResponseAllOfValuesOverrideFileRawValues) Set(val *HelmResponseAllOfValuesOverrideFileRawValues) {
	v.value = val
	v.isSet = true
}

func (v NullableHelmResponseAllOfValuesOverrideFileRawValues) IsSet() bool {
	return v.isSet
}

func (v *NullableHelmResponseAllOfValuesOverrideFileRawValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelmResponseAllOfValuesOverrideFileRawValues(val *HelmResponseAllOfValuesOverrideFileRawValues) *NullableHelmResponseAllOfValuesOverrideFileRawValues {
	return &NullableHelmResponseAllOfValuesOverrideFileRawValues{value: val, isSet: true}
}

func (v NullableHelmResponseAllOfValuesOverrideFileRawValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelmResponseAllOfValuesOverrideFileRawValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
