/*
Qovery API

- Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.

API version: 1.0.4
Contact: support+api+documentation@qovery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterPlatformBindingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterPlatformBindingResponse{}

// ClusterPlatformBindingResponse struct for ClusterPlatformBindingResponse
type ClusterPlatformBindingResponse struct {
	ClusterId       string          `json:"clusterId"`
	OrganizationId  string          `json:"organizationId"`
	TemplateKey     string          `json:"templateKey"`
	TemplateVersion string          `json:"templateVersion"`
	LayerSelections map[string]bool `json:"layerSelections"`
	// Component configuration values keyed by component key
	ManagedConfig map[string]map[string]interface{} `json:"managedConfig"`
	// String values keyed first by component key and then by input key
	CustomerProvidedInputs map[string]map[string]string          `json:"customerProvidedInputs"`
	Layers                 []ClusterPlatformBindingLayerResponse `json:"layers"`
	AdditionalProperties   map[string]interface{}
}

type _ClusterPlatformBindingResponse ClusterPlatformBindingResponse

// NewClusterPlatformBindingResponse instantiates a new ClusterPlatformBindingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterPlatformBindingResponse(clusterId string, organizationId string, templateKey string, templateVersion string, layerSelections map[string]bool, managedConfig map[string]map[string]interface{}, customerProvidedInputs map[string]map[string]string, layers []ClusterPlatformBindingLayerResponse) *ClusterPlatformBindingResponse {
	this := ClusterPlatformBindingResponse{}
	this.ClusterId = clusterId
	this.OrganizationId = organizationId
	this.TemplateKey = templateKey
	this.TemplateVersion = templateVersion
	this.LayerSelections = layerSelections
	this.ManagedConfig = managedConfig
	this.CustomerProvidedInputs = customerProvidedInputs
	this.Layers = layers
	return &this
}

// NewClusterPlatformBindingResponseWithDefaults instantiates a new ClusterPlatformBindingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterPlatformBindingResponseWithDefaults() *ClusterPlatformBindingResponse {
	this := ClusterPlatformBindingResponse{}
	return &this
}

// GetClusterId returns the ClusterId field value
func (o *ClusterPlatformBindingResponse) GetClusterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value
// and a boolean to check if the value has been set.
func (o *ClusterPlatformBindingResponse) GetClusterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterId, true
}

// SetClusterId sets field value
func (o *ClusterPlatformBindingResponse) SetClusterId(v string) {
	o.ClusterId = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *ClusterPlatformBindingResponse) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *ClusterPlatformBindingResponse) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *ClusterPlatformBindingResponse) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetTemplateKey returns the TemplateKey field value
func (o *ClusterPlatformBindingResponse) GetTemplateKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateKey
}

// GetTemplateKeyOk returns a tuple with the TemplateKey field value
// and a boolean to check if the value has been set.
func (o *ClusterPlatformBindingResponse) GetTemplateKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateKey, true
}

// SetTemplateKey sets field value
func (o *ClusterPlatformBindingResponse) SetTemplateKey(v string) {
	o.TemplateKey = v
}

// GetTemplateVersion returns the TemplateVersion field value
func (o *ClusterPlatformBindingResponse) GetTemplateVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateVersion
}

// GetTemplateVersionOk returns a tuple with the TemplateVersion field value
// and a boolean to check if the value has been set.
func (o *ClusterPlatformBindingResponse) GetTemplateVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateVersion, true
}

// SetTemplateVersion sets field value
func (o *ClusterPlatformBindingResponse) SetTemplateVersion(v string) {
	o.TemplateVersion = v
}

// GetLayerSelections returns the LayerSelections field value
func (o *ClusterPlatformBindingResponse) GetLayerSelections() map[string]bool {
	if o == nil {
		var ret map[string]bool
		return ret
	}

	return o.LayerSelections
}

// GetLayerSelectionsOk returns a tuple with the LayerSelections field value
// and a boolean to check if the value has been set.
func (o *ClusterPlatformBindingResponse) GetLayerSelectionsOk() (*map[string]bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LayerSelections, true
}

// SetLayerSelections sets field value
func (o *ClusterPlatformBindingResponse) SetLayerSelections(v map[string]bool) {
	o.LayerSelections = v
}

// GetManagedConfig returns the ManagedConfig field value
func (o *ClusterPlatformBindingResponse) GetManagedConfig() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.ManagedConfig
}

// GetManagedConfigOk returns a tuple with the ManagedConfig field value
// and a boolean to check if the value has been set.
func (o *ClusterPlatformBindingResponse) GetManagedConfigOk() (*map[string]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ManagedConfig, true
}

// SetManagedConfig sets field value
func (o *ClusterPlatformBindingResponse) SetManagedConfig(v map[string]map[string]interface{}) {
	o.ManagedConfig = v
}

// GetCustomerProvidedInputs returns the CustomerProvidedInputs field value
func (o *ClusterPlatformBindingResponse) GetCustomerProvidedInputs() map[string]map[string]string {
	if o == nil {
		var ret map[string]map[string]string
		return ret
	}

	return o.CustomerProvidedInputs
}

// GetCustomerProvidedInputsOk returns a tuple with the CustomerProvidedInputs field value
// and a boolean to check if the value has been set.
func (o *ClusterPlatformBindingResponse) GetCustomerProvidedInputsOk() (*map[string]map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerProvidedInputs, true
}

// SetCustomerProvidedInputs sets field value
func (o *ClusterPlatformBindingResponse) SetCustomerProvidedInputs(v map[string]map[string]string) {
	o.CustomerProvidedInputs = v
}

// GetLayers returns the Layers field value
func (o *ClusterPlatformBindingResponse) GetLayers() []ClusterPlatformBindingLayerResponse {
	if o == nil {
		var ret []ClusterPlatformBindingLayerResponse
		return ret
	}

	return o.Layers
}

// GetLayersOk returns a tuple with the Layers field value
// and a boolean to check if the value has been set.
func (o *ClusterPlatformBindingResponse) GetLayersOk() ([]ClusterPlatformBindingLayerResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Layers, true
}

// SetLayers sets field value
func (o *ClusterPlatformBindingResponse) SetLayers(v []ClusterPlatformBindingLayerResponse) {
	o.Layers = v
}

func (o ClusterPlatformBindingResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterPlatformBindingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clusterId"] = o.ClusterId
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["templateKey"] = o.TemplateKey
	toSerialize["templateVersion"] = o.TemplateVersion
	toSerialize["layerSelections"] = o.LayerSelections
	toSerialize["managedConfig"] = o.ManagedConfig
	toSerialize["customerProvidedInputs"] = o.CustomerProvidedInputs
	toSerialize["layers"] = o.Layers

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterPlatformBindingResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"clusterId",
		"organizationId",
		"templateKey",
		"templateVersion",
		"layerSelections",
		"managedConfig",
		"customerProvidedInputs",
		"layers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterPlatformBindingResponse := _ClusterPlatformBindingResponse{}

	err = json.Unmarshal(data, &varClusterPlatformBindingResponse)

	if err != nil {
		return err
	}

	*o = ClusterPlatformBindingResponse(varClusterPlatformBindingResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "clusterId")
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "templateKey")
		delete(additionalProperties, "templateVersion")
		delete(additionalProperties, "layerSelections")
		delete(additionalProperties, "managedConfig")
		delete(additionalProperties, "customerProvidedInputs")
		delete(additionalProperties, "layers")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterPlatformBindingResponse struct {
	value *ClusterPlatformBindingResponse
	isSet bool
}

func (v NullableClusterPlatformBindingResponse) Get() *ClusterPlatformBindingResponse {
	return v.value
}

func (v *NullableClusterPlatformBindingResponse) Set(val *ClusterPlatformBindingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterPlatformBindingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterPlatformBindingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterPlatformBindingResponse(val *ClusterPlatformBindingResponse) *NullableClusterPlatformBindingResponse {
	return &NullableClusterPlatformBindingResponse{value: val, isSet: true}
}

func (v NullableClusterPlatformBindingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterPlatformBindingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
