/*
Qovery API

- Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.

API version: 1.0.3
Contact: support+api+documentation@qovery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery

import (
	"encoding/json"
)

// ListAvailableContainerRegistry200Response struct for ListAvailableContainerRegistry200Response
type ListAvailableContainerRegistry200Response struct {
	Results []AvailableContainerRegistryResponse `json:"results,omitempty"`
}

// NewListAvailableContainerRegistry200Response instantiates a new ListAvailableContainerRegistry200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAvailableContainerRegistry200Response() *ListAvailableContainerRegistry200Response {
	this := ListAvailableContainerRegistry200Response{}
	return &this
}

// NewListAvailableContainerRegistry200ResponseWithDefaults instantiates a new ListAvailableContainerRegistry200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAvailableContainerRegistry200ResponseWithDefaults() *ListAvailableContainerRegistry200Response {
	this := ListAvailableContainerRegistry200Response{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *ListAvailableContainerRegistry200Response) GetResults() []AvailableContainerRegistryResponse {
	if o == nil || o.Results == nil {
		var ret []AvailableContainerRegistryResponse
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAvailableContainerRegistry200Response) GetResultsOk() ([]AvailableContainerRegistryResponse, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *ListAvailableContainerRegistry200Response) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given []AvailableContainerRegistryResponse and assigns it to the Results field.
func (o *ListAvailableContainerRegistry200Response) SetResults(v []AvailableContainerRegistryResponse) {
	o.Results = v
}

func (o ListAvailableContainerRegistry200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableListAvailableContainerRegistry200Response struct {
	value *ListAvailableContainerRegistry200Response
	isSet bool
}

func (v NullableListAvailableContainerRegistry200Response) Get() *ListAvailableContainerRegistry200Response {
	return v.value
}

func (v *NullableListAvailableContainerRegistry200Response) Set(val *ListAvailableContainerRegistry200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListAvailableContainerRegistry200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListAvailableContainerRegistry200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAvailableContainerRegistry200Response(val *ListAvailableContainerRegistry200Response) *NullableListAvailableContainerRegistry200Response {
	return &NullableListAvailableContainerRegistry200Response{value: val, isSet: true}
}

func (v NullableListAvailableContainerRegistry200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAvailableContainerRegistry200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
