/*
Qovery API

- Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.

API version: 1.0.3
Contact: support+api+documentation@qovery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery

import (
	"encoding/json"
)

// GetEnvironmentStatusesWithStages200ResponseStages struct for GetEnvironmentStatusesWithStages200ResponseStages
type GetEnvironmentStatusesWithStages200ResponseStages struct {
	Results []GetEnvironmentStatusesWithStages200ResponseStagesResultsInner `json:"results,omitempty"`
}

// NewGetEnvironmentStatusesWithStages200ResponseStages instantiates a new GetEnvironmentStatusesWithStages200ResponseStages object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEnvironmentStatusesWithStages200ResponseStages() *GetEnvironmentStatusesWithStages200ResponseStages {
	this := GetEnvironmentStatusesWithStages200ResponseStages{}
	return &this
}

// NewGetEnvironmentStatusesWithStages200ResponseStagesWithDefaults instantiates a new GetEnvironmentStatusesWithStages200ResponseStages object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEnvironmentStatusesWithStages200ResponseStagesWithDefaults() *GetEnvironmentStatusesWithStages200ResponseStages {
	this := GetEnvironmentStatusesWithStages200ResponseStages{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *GetEnvironmentStatusesWithStages200ResponseStages) GetResults() []GetEnvironmentStatusesWithStages200ResponseStagesResultsInner {
	if o == nil || o.Results == nil {
		var ret []GetEnvironmentStatusesWithStages200ResponseStagesResultsInner
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEnvironmentStatusesWithStages200ResponseStages) GetResultsOk() ([]GetEnvironmentStatusesWithStages200ResponseStagesResultsInner, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *GetEnvironmentStatusesWithStages200ResponseStages) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given []GetEnvironmentStatusesWithStages200ResponseStagesResultsInner and assigns it to the Results field.
func (o *GetEnvironmentStatusesWithStages200ResponseStages) SetResults(v []GetEnvironmentStatusesWithStages200ResponseStagesResultsInner) {
	o.Results = v
}

func (o GetEnvironmentStatusesWithStages200ResponseStages) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableGetEnvironmentStatusesWithStages200ResponseStages struct {
	value *GetEnvironmentStatusesWithStages200ResponseStages
	isSet bool
}

func (v NullableGetEnvironmentStatusesWithStages200ResponseStages) Get() *GetEnvironmentStatusesWithStages200ResponseStages {
	return v.value
}

func (v *NullableGetEnvironmentStatusesWithStages200ResponseStages) Set(val *GetEnvironmentStatusesWithStages200ResponseStages) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEnvironmentStatusesWithStages200ResponseStages) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEnvironmentStatusesWithStages200ResponseStages) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEnvironmentStatusesWithStages200ResponseStages(val *GetEnvironmentStatusesWithStages200ResponseStages) *NullableGetEnvironmentStatusesWithStages200ResponseStages {
	return &NullableGetEnvironmentStatusesWithStages200ResponseStages{value: val, isSet: true}
}

func (v NullableGetEnvironmentStatusesWithStages200ResponseStages) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEnvironmentStatusesWithStages200ResponseStages) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
