/*
Qovery API

- Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.

API version: 1.0.4
Contact: support+api+documentation@qovery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery

import (
	"encoding/json"
	"fmt"
)

// checks if the BlueprintManifestVariableField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlueprintManifestVariableField{}

// BlueprintManifestVariableField An editable form input the user fills in (from spec.variables).
type BlueprintManifestVariableField struct {
	Kind                 string                     `json:"kind"`
	Name                 string                     `json:"name"`
	Type                 BlueprintManifestFieldType `json:"type"`
	Required             bool                       `json:"required"`
	IsSecret             bool                       `json:"is_secret"`
	Description          NullableString             `json:"description,omitempty"`
	AllowedValues        []string                   `json:"allowed_values,omitempty"`
	DefaultValue         NullableString             `json:"default_value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BlueprintManifestVariableField BlueprintManifestVariableField

// NewBlueprintManifestVariableField instantiates a new BlueprintManifestVariableField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlueprintManifestVariableField(kind string, name string, type_ BlueprintManifestFieldType, required bool, isSecret bool) *BlueprintManifestVariableField {
	this := BlueprintManifestVariableField{}
	this.Kind = kind
	this.Name = name
	this.Type = type_
	this.Required = required
	this.IsSecret = isSecret
	return &this
}

// NewBlueprintManifestVariableFieldWithDefaults instantiates a new BlueprintManifestVariableField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlueprintManifestVariableFieldWithDefaults() *BlueprintManifestVariableField {
	this := BlueprintManifestVariableField{}
	return &this
}

// GetKind returns the Kind field value
func (o *BlueprintManifestVariableField) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *BlueprintManifestVariableField) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *BlueprintManifestVariableField) SetKind(v string) {
	o.Kind = v
}

// GetName returns the Name field value
func (o *BlueprintManifestVariableField) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BlueprintManifestVariableField) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BlueprintManifestVariableField) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *BlueprintManifestVariableField) GetType() BlueprintManifestFieldType {
	if o == nil {
		var ret BlueprintManifestFieldType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BlueprintManifestVariableField) GetTypeOk() (*BlueprintManifestFieldType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BlueprintManifestVariableField) SetType(v BlueprintManifestFieldType) {
	o.Type = v
}

// GetRequired returns the Required field value
func (o *BlueprintManifestVariableField) GetRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Required
}

// GetRequiredOk returns a tuple with the Required field value
// and a boolean to check if the value has been set.
func (o *BlueprintManifestVariableField) GetRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Required, true
}

// SetRequired sets field value
func (o *BlueprintManifestVariableField) SetRequired(v bool) {
	o.Required = v
}

// GetIsSecret returns the IsSecret field value
func (o *BlueprintManifestVariableField) GetIsSecret() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsSecret
}

// GetIsSecretOk returns a tuple with the IsSecret field value
// and a boolean to check if the value has been set.
func (o *BlueprintManifestVariableField) GetIsSecretOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsSecret, true
}

// SetIsSecret sets field value
func (o *BlueprintManifestVariableField) SetIsSecret(v bool) {
	o.IsSecret = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlueprintManifestVariableField) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlueprintManifestVariableField) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *BlueprintManifestVariableField) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *BlueprintManifestVariableField) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *BlueprintManifestVariableField) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *BlueprintManifestVariableField) UnsetDescription() {
	o.Description.Unset()
}

// GetAllowedValues returns the AllowedValues field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlueprintManifestVariableField) GetAllowedValues() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AllowedValues
}

// GetAllowedValuesOk returns a tuple with the AllowedValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlueprintManifestVariableField) GetAllowedValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedValues) {
		return nil, false
	}
	return o.AllowedValues, true
}

// HasAllowedValues returns a boolean if a field has been set.
func (o *BlueprintManifestVariableField) HasAllowedValues() bool {
	if o != nil && !IsNil(o.AllowedValues) {
		return true
	}

	return false
}

// SetAllowedValues gets a reference to the given []string and assigns it to the AllowedValues field.
func (o *BlueprintManifestVariableField) SetAllowedValues(v []string) {
	o.AllowedValues = v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlueprintManifestVariableField) GetDefaultValue() string {
	if o == nil || IsNil(o.DefaultValue.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultValue.Get()
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlueprintManifestVariableField) GetDefaultValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultValue.Get(), o.DefaultValue.IsSet()
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *BlueprintManifestVariableField) HasDefaultValue() bool {
	if o != nil && o.DefaultValue.IsSet() {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given NullableString and assigns it to the DefaultValue field.
func (o *BlueprintManifestVariableField) SetDefaultValue(v string) {
	o.DefaultValue.Set(&v)
}

// SetDefaultValueNil sets the value for DefaultValue to be an explicit nil
func (o *BlueprintManifestVariableField) SetDefaultValueNil() {
	o.DefaultValue.Set(nil)
}

// UnsetDefaultValue ensures that no value is present for DefaultValue, not even an explicit nil
func (o *BlueprintManifestVariableField) UnsetDefaultValue() {
	o.DefaultValue.Unset()
}

func (o BlueprintManifestVariableField) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlueprintManifestVariableField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["required"] = o.Required
	toSerialize["is_secret"] = o.IsSecret
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.AllowedValues != nil {
		toSerialize["allowed_values"] = o.AllowedValues
	}
	if o.DefaultValue.IsSet() {
		toSerialize["default_value"] = o.DefaultValue.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BlueprintManifestVariableField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"name",
		"type",
		"required",
		"is_secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlueprintManifestVariableField := _BlueprintManifestVariableField{}

	err = json.Unmarshal(data, &varBlueprintManifestVariableField)

	if err != nil {
		return err
	}

	*o = BlueprintManifestVariableField(varBlueprintManifestVariableField)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "kind")
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		delete(additionalProperties, "required")
		delete(additionalProperties, "is_secret")
		delete(additionalProperties, "description")
		delete(additionalProperties, "allowed_values")
		delete(additionalProperties, "default_value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBlueprintManifestVariableField struct {
	value *BlueprintManifestVariableField
	isSet bool
}

func (v NullableBlueprintManifestVariableField) Get() *BlueprintManifestVariableField {
	return v.value
}

func (v *NullableBlueprintManifestVariableField) Set(val *BlueprintManifestVariableField) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintManifestVariableField) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintManifestVariableField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintManifestVariableField(val *BlueprintManifestVariableField) *NullableBlueprintManifestVariableField {
	return &NullableBlueprintManifestVariableField{value: val, isSet: true}
}

func (v NullableBlueprintManifestVariableField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintManifestVariableField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
