/*
Qovery API

- Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.

API version: 1.0.4
Contact: support+api+documentation@qovery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ClusterStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterStatus{}

// ClusterStatus struct for ClusterStatus
type ClusterStatus struct {
	ClusterId               string                `json:"cluster_id"`
	Status                  ClusterStateEnum      `json:"status"`
	IsDeployed              bool                  `json:"is_deployed"`
	NextK8sAvailableVersion NullableString        `json:"next_k8s_available_version,omitempty"`
	LastExecutionId         NullableString        `json:"last_execution_id,omitempty"`
	ClusterLock             NullableClusterLock   `json:"cluster_lock,omitempty"`
	LastDeploymentDate      NullableTime          `json:"last_deployment_date,omitempty"`
	Reason                  DeploymentInfraReason `json:"reason"`
	AdditionalProperties    map[string]interface{}
}

type _ClusterStatus ClusterStatus

// NewClusterStatus instantiates a new ClusterStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterStatus(clusterId string, status ClusterStateEnum, isDeployed bool, reason DeploymentInfraReason) *ClusterStatus {
	this := ClusterStatus{}
	this.ClusterId = clusterId
	this.Status = status
	this.IsDeployed = isDeployed
	this.Reason = reason
	return &this
}

// NewClusterStatusWithDefaults instantiates a new ClusterStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterStatusWithDefaults() *ClusterStatus {
	this := ClusterStatus{}
	return &this
}

// GetClusterId returns the ClusterId field value
func (o *ClusterStatus) GetClusterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value
// and a boolean to check if the value has been set.
func (o *ClusterStatus) GetClusterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterId, true
}

// SetClusterId sets field value
func (o *ClusterStatus) SetClusterId(v string) {
	o.ClusterId = v
}

// GetStatus returns the Status field value
func (o *ClusterStatus) GetStatus() ClusterStateEnum {
	if o == nil {
		var ret ClusterStateEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ClusterStatus) GetStatusOk() (*ClusterStateEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ClusterStatus) SetStatus(v ClusterStateEnum) {
	o.Status = v
}

// GetIsDeployed returns the IsDeployed field value
func (o *ClusterStatus) GetIsDeployed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDeployed
}

// GetIsDeployedOk returns a tuple with the IsDeployed field value
// and a boolean to check if the value has been set.
func (o *ClusterStatus) GetIsDeployedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDeployed, true
}

// SetIsDeployed sets field value
func (o *ClusterStatus) SetIsDeployed(v bool) {
	o.IsDeployed = v
}

// GetNextK8sAvailableVersion returns the NextK8sAvailableVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClusterStatus) GetNextK8sAvailableVersion() string {
	if o == nil || IsNil(o.NextK8sAvailableVersion.Get()) {
		var ret string
		return ret
	}
	return *o.NextK8sAvailableVersion.Get()
}

// GetNextK8sAvailableVersionOk returns a tuple with the NextK8sAvailableVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterStatus) GetNextK8sAvailableVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextK8sAvailableVersion.Get(), o.NextK8sAvailableVersion.IsSet()
}

// HasNextK8sAvailableVersion returns a boolean if a field has been set.
func (o *ClusterStatus) HasNextK8sAvailableVersion() bool {
	if o != nil && o.NextK8sAvailableVersion.IsSet() {
		return true
	}

	return false
}

// SetNextK8sAvailableVersion gets a reference to the given NullableString and assigns it to the NextK8sAvailableVersion field.
func (o *ClusterStatus) SetNextK8sAvailableVersion(v string) {
	o.NextK8sAvailableVersion.Set(&v)
}

// SetNextK8sAvailableVersionNil sets the value for NextK8sAvailableVersion to be an explicit nil
func (o *ClusterStatus) SetNextK8sAvailableVersionNil() {
	o.NextK8sAvailableVersion.Set(nil)
}

// UnsetNextK8sAvailableVersion ensures that no value is present for NextK8sAvailableVersion, not even an explicit nil
func (o *ClusterStatus) UnsetNextK8sAvailableVersion() {
	o.NextK8sAvailableVersion.Unset()
}

// GetLastExecutionId returns the LastExecutionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClusterStatus) GetLastExecutionId() string {
	if o == nil || IsNil(o.LastExecutionId.Get()) {
		var ret string
		return ret
	}
	return *o.LastExecutionId.Get()
}

// GetLastExecutionIdOk returns a tuple with the LastExecutionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterStatus) GetLastExecutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastExecutionId.Get(), o.LastExecutionId.IsSet()
}

// HasLastExecutionId returns a boolean if a field has been set.
func (o *ClusterStatus) HasLastExecutionId() bool {
	if o != nil && o.LastExecutionId.IsSet() {
		return true
	}

	return false
}

// SetLastExecutionId gets a reference to the given NullableString and assigns it to the LastExecutionId field.
func (o *ClusterStatus) SetLastExecutionId(v string) {
	o.LastExecutionId.Set(&v)
}

// SetLastExecutionIdNil sets the value for LastExecutionId to be an explicit nil
func (o *ClusterStatus) SetLastExecutionIdNil() {
	o.LastExecutionId.Set(nil)
}

// UnsetLastExecutionId ensures that no value is present for LastExecutionId, not even an explicit nil
func (o *ClusterStatus) UnsetLastExecutionId() {
	o.LastExecutionId.Unset()
}

// GetClusterLock returns the ClusterLock field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClusterStatus) GetClusterLock() ClusterLock {
	if o == nil || IsNil(o.ClusterLock.Get()) {
		var ret ClusterLock
		return ret
	}
	return *o.ClusterLock.Get()
}

// GetClusterLockOk returns a tuple with the ClusterLock field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterStatus) GetClusterLockOk() (*ClusterLock, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClusterLock.Get(), o.ClusterLock.IsSet()
}

// HasClusterLock returns a boolean if a field has been set.
func (o *ClusterStatus) HasClusterLock() bool {
	if o != nil && o.ClusterLock.IsSet() {
		return true
	}

	return false
}

// SetClusterLock gets a reference to the given NullableClusterLock and assigns it to the ClusterLock field.
func (o *ClusterStatus) SetClusterLock(v ClusterLock) {
	o.ClusterLock.Set(&v)
}

// SetClusterLockNil sets the value for ClusterLock to be an explicit nil
func (o *ClusterStatus) SetClusterLockNil() {
	o.ClusterLock.Set(nil)
}

// UnsetClusterLock ensures that no value is present for ClusterLock, not even an explicit nil
func (o *ClusterStatus) UnsetClusterLock() {
	o.ClusterLock.Unset()
}

// GetLastDeploymentDate returns the LastDeploymentDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClusterStatus) GetLastDeploymentDate() time.Time {
	if o == nil || IsNil(o.LastDeploymentDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastDeploymentDate.Get()
}

// GetLastDeploymentDateOk returns a tuple with the LastDeploymentDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterStatus) GetLastDeploymentDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastDeploymentDate.Get(), o.LastDeploymentDate.IsSet()
}

// HasLastDeploymentDate returns a boolean if a field has been set.
func (o *ClusterStatus) HasLastDeploymentDate() bool {
	if o != nil && o.LastDeploymentDate.IsSet() {
		return true
	}

	return false
}

// SetLastDeploymentDate gets a reference to the given NullableTime and assigns it to the LastDeploymentDate field.
func (o *ClusterStatus) SetLastDeploymentDate(v time.Time) {
	o.LastDeploymentDate.Set(&v)
}

// SetLastDeploymentDateNil sets the value for LastDeploymentDate to be an explicit nil
func (o *ClusterStatus) SetLastDeploymentDateNil() {
	o.LastDeploymentDate.Set(nil)
}

// UnsetLastDeploymentDate ensures that no value is present for LastDeploymentDate, not even an explicit nil
func (o *ClusterStatus) UnsetLastDeploymentDate() {
	o.LastDeploymentDate.Unset()
}

// GetReason returns the Reason field value
func (o *ClusterStatus) GetReason() DeploymentInfraReason {
	if o == nil {
		var ret DeploymentInfraReason
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *ClusterStatus) GetReasonOk() (*DeploymentInfraReason, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *ClusterStatus) SetReason(v DeploymentInfraReason) {
	o.Reason = v
}

func (o ClusterStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cluster_id"] = o.ClusterId
	toSerialize["status"] = o.Status
	toSerialize["is_deployed"] = o.IsDeployed
	if o.NextK8sAvailableVersion.IsSet() {
		toSerialize["next_k8s_available_version"] = o.NextK8sAvailableVersion.Get()
	}
	if o.LastExecutionId.IsSet() {
		toSerialize["last_execution_id"] = o.LastExecutionId.Get()
	}
	if o.ClusterLock.IsSet() {
		toSerialize["cluster_lock"] = o.ClusterLock.Get()
	}
	if o.LastDeploymentDate.IsSet() {
		toSerialize["last_deployment_date"] = o.LastDeploymentDate.Get()
	}
	toSerialize["reason"] = o.Reason

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cluster_id",
		"status",
		"is_deployed",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterStatus := _ClusterStatus{}

	err = json.Unmarshal(data, &varClusterStatus)

	if err != nil {
		return err
	}

	*o = ClusterStatus(varClusterStatus)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cluster_id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "is_deployed")
		delete(additionalProperties, "next_k8s_available_version")
		delete(additionalProperties, "last_execution_id")
		delete(additionalProperties, "cluster_lock")
		delete(additionalProperties, "last_deployment_date")
		delete(additionalProperties, "reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterStatus struct {
	value *ClusterStatus
	isSet bool
}

func (v NullableClusterStatus) Get() *ClusterStatus {
	return v.value
}

func (v *NullableClusterStatus) Set(val *ClusterStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterStatus(val *ClusterStatus) *NullableClusterStatus {
	return &NullableClusterStatus{value: val, isSet: true}
}

func (v NullableClusterStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
