/*
[BETA] Qovery API

- Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is in Beta and still in progress. Some endpoints are not available yet. 

API version: 1.0.0
Contact: support+api+documentation@qovery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery

import (
	"encoding/json"
	"time"
)

// ProjectDeploymentRuleResponse struct for ProjectDeploymentRuleResponse
type ProjectDeploymentRuleResponse struct {
	Id string `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// name is case insensitive
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	Mode string `json:"mode"`
	Cluster string `json:"cluster"`
	AutoDeploy *bool `json:"auto_deploy,omitempty"`
	AutoStop bool `json:"auto_stop"`
	// specify value only if auto_stop = false
	Timezone *string `json:"timezone,omitempty"`
	// specify value only if auto_stop = false
	StartTime NullableTime `json:"start_time,omitempty"`
	// specify value only if auto_stop = false
	StopTime NullableTime `json:"stop_time,omitempty"`
	// specify value only if auto_stop = false
	Weekdays []string `json:"weekdays,omitempty"`
}

// NewProjectDeploymentRuleResponse instantiates a new ProjectDeploymentRuleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectDeploymentRuleResponse(id string, createdAt time.Time, name string, mode string, cluster string, autoStop bool) *ProjectDeploymentRuleResponse {
	this := ProjectDeploymentRuleResponse{}
	this.Id = id
	this.CreatedAt = createdAt
	this.Name = name
	this.Mode = mode
	this.Cluster = cluster
	var autoDeploy bool = true
	this.AutoDeploy = &autoDeploy
	this.AutoStop = autoStop
	var timezone string = "Europe/London"
	this.Timezone = &timezone
	return &this
}

// NewProjectDeploymentRuleResponseWithDefaults instantiates a new ProjectDeploymentRuleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectDeploymentRuleResponseWithDefaults() *ProjectDeploymentRuleResponse {
	this := ProjectDeploymentRuleResponse{}
	var autoDeploy bool = true
	this.AutoDeploy = &autoDeploy
	var autoStop bool = false
	this.AutoStop = autoStop
	var timezone string = "Europe/London"
	this.Timezone = &timezone
	return &this
}

// GetId returns the Id field value
func (o *ProjectDeploymentRuleResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProjectDeploymentRuleResponse) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProjectDeploymentRuleResponse) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ProjectDeploymentRuleResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ProjectDeploymentRuleResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ProjectDeploymentRuleResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ProjectDeploymentRuleResponse) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDeploymentRuleResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ProjectDeploymentRuleResponse) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ProjectDeploymentRuleResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetName returns the Name field value
func (o *ProjectDeploymentRuleResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProjectDeploymentRuleResponse) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProjectDeploymentRuleResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProjectDeploymentRuleResponse) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDeploymentRuleResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProjectDeploymentRuleResponse) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ProjectDeploymentRuleResponse) SetDescription(v string) {
	o.Description = &v
}

// GetMode returns the Mode field value
func (o *ProjectDeploymentRuleResponse) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *ProjectDeploymentRuleResponse) GetModeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *ProjectDeploymentRuleResponse) SetMode(v string) {
	o.Mode = v
}

// GetCluster returns the Cluster field value
func (o *ProjectDeploymentRuleResponse) GetCluster() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value
// and a boolean to check if the value has been set.
func (o *ProjectDeploymentRuleResponse) GetClusterOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Cluster, true
}

// SetCluster sets field value
func (o *ProjectDeploymentRuleResponse) SetCluster(v string) {
	o.Cluster = v
}

// GetAutoDeploy returns the AutoDeploy field value if set, zero value otherwise.
func (o *ProjectDeploymentRuleResponse) GetAutoDeploy() bool {
	if o == nil || o.AutoDeploy == nil {
		var ret bool
		return ret
	}
	return *o.AutoDeploy
}

// GetAutoDeployOk returns a tuple with the AutoDeploy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDeploymentRuleResponse) GetAutoDeployOk() (*bool, bool) {
	if o == nil || o.AutoDeploy == nil {
		return nil, false
	}
	return o.AutoDeploy, true
}

// HasAutoDeploy returns a boolean if a field has been set.
func (o *ProjectDeploymentRuleResponse) HasAutoDeploy() bool {
	if o != nil && o.AutoDeploy != nil {
		return true
	}

	return false
}

// SetAutoDeploy gets a reference to the given bool and assigns it to the AutoDeploy field.
func (o *ProjectDeploymentRuleResponse) SetAutoDeploy(v bool) {
	o.AutoDeploy = &v
}

// GetAutoStop returns the AutoStop field value
func (o *ProjectDeploymentRuleResponse) GetAutoStop() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AutoStop
}

// GetAutoStopOk returns a tuple with the AutoStop field value
// and a boolean to check if the value has been set.
func (o *ProjectDeploymentRuleResponse) GetAutoStopOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AutoStop, true
}

// SetAutoStop sets field value
func (o *ProjectDeploymentRuleResponse) SetAutoStop(v bool) {
	o.AutoStop = v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *ProjectDeploymentRuleResponse) GetTimezone() string {
	if o == nil || o.Timezone == nil {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDeploymentRuleResponse) GetTimezoneOk() (*string, bool) {
	if o == nil || o.Timezone == nil {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *ProjectDeploymentRuleResponse) HasTimezone() bool {
	if o != nil && o.Timezone != nil {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *ProjectDeploymentRuleResponse) SetTimezone(v string) {
	o.Timezone = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectDeploymentRuleResponse) GetStartTime() time.Time {
	if o == nil || o.StartTime.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.StartTime.Get()
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectDeploymentRuleResponse) GetStartTimeOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.StartTime.Get(), o.StartTime.IsSet()
}

// HasStartTime returns a boolean if a field has been set.
func (o *ProjectDeploymentRuleResponse) HasStartTime() bool {
	if o != nil && o.StartTime.IsSet() {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given NullableTime and assigns it to the StartTime field.
func (o *ProjectDeploymentRuleResponse) SetStartTime(v time.Time) {
	o.StartTime.Set(&v)
}
// SetStartTimeNil sets the value for StartTime to be an explicit nil
func (o *ProjectDeploymentRuleResponse) SetStartTimeNil() {
	o.StartTime.Set(nil)
}

// UnsetStartTime ensures that no value is present for StartTime, not even an explicit nil
func (o *ProjectDeploymentRuleResponse) UnsetStartTime() {
	o.StartTime.Unset()
}

// GetStopTime returns the StopTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectDeploymentRuleResponse) GetStopTime() time.Time {
	if o == nil || o.StopTime.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.StopTime.Get()
}

// GetStopTimeOk returns a tuple with the StopTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectDeploymentRuleResponse) GetStopTimeOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.StopTime.Get(), o.StopTime.IsSet()
}

// HasStopTime returns a boolean if a field has been set.
func (o *ProjectDeploymentRuleResponse) HasStopTime() bool {
	if o != nil && o.StopTime.IsSet() {
		return true
	}

	return false
}

// SetStopTime gets a reference to the given NullableTime and assigns it to the StopTime field.
func (o *ProjectDeploymentRuleResponse) SetStopTime(v time.Time) {
	o.StopTime.Set(&v)
}
// SetStopTimeNil sets the value for StopTime to be an explicit nil
func (o *ProjectDeploymentRuleResponse) SetStopTimeNil() {
	o.StopTime.Set(nil)
}

// UnsetStopTime ensures that no value is present for StopTime, not even an explicit nil
func (o *ProjectDeploymentRuleResponse) UnsetStopTime() {
	o.StopTime.Unset()
}

// GetWeekdays returns the Weekdays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectDeploymentRuleResponse) GetWeekdays() []string {
	if o == nil  {
		var ret []string
		return ret
	}
	return o.Weekdays
}

// GetWeekdaysOk returns a tuple with the Weekdays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectDeploymentRuleResponse) GetWeekdaysOk() ([]string, bool) {
	if o == nil || o.Weekdays == nil {
		return nil, false
	}
	return o.Weekdays, true
}

// HasWeekdays returns a boolean if a field has been set.
func (o *ProjectDeploymentRuleResponse) HasWeekdays() bool {
	if o != nil && o.Weekdays != nil {
		return true
	}

	return false
}

// SetWeekdays gets a reference to the given []string and assigns it to the Weekdays field.
func (o *ProjectDeploymentRuleResponse) SetWeekdays(v []string) {
	o.Weekdays = v
}

func (o ProjectDeploymentRuleResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["mode"] = o.Mode
	}
	if true {
		toSerialize["cluster"] = o.Cluster
	}
	if o.AutoDeploy != nil {
		toSerialize["auto_deploy"] = o.AutoDeploy
	}
	if true {
		toSerialize["auto_stop"] = o.AutoStop
	}
	if o.Timezone != nil {
		toSerialize["timezone"] = o.Timezone
	}
	if o.StartTime.IsSet() {
		toSerialize["start_time"] = o.StartTime.Get()
	}
	if o.StopTime.IsSet() {
		toSerialize["stop_time"] = o.StopTime.Get()
	}
	if o.Weekdays != nil {
		toSerialize["weekdays"] = o.Weekdays
	}
	return json.Marshal(toSerialize)
}

type NullableProjectDeploymentRuleResponse struct {
	value *ProjectDeploymentRuleResponse
	isSet bool
}

func (v NullableProjectDeploymentRuleResponse) Get() *ProjectDeploymentRuleResponse {
	return v.value
}

func (v *NullableProjectDeploymentRuleResponse) Set(val *ProjectDeploymentRuleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectDeploymentRuleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectDeploymentRuleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectDeploymentRuleResponse(val *ProjectDeploymentRuleResponse) *NullableProjectDeploymentRuleResponse {
	return &NullableProjectDeploymentRuleResponse{value: val, isSet: true}
}

func (v NullableProjectDeploymentRuleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectDeploymentRuleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


