/*
Qovery API

- Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.

API version: 1.0.3
Contact: support+api+documentation@qovery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery

import (
	"encoding/json"
)

// InlineResponse200 struct for InlineResponse200
type InlineResponse200 struct {
	DeploymentDelayStartTimeSec *int32 `json:"deployment.delay_start_time_sec,omitempty"`
	BuildTimeoutMaxSec          *int32 `json:"build.timeout_max_sec,omitempty"`
}

// NewInlineResponse200 instantiates a new InlineResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200() *InlineResponse200 {
	this := InlineResponse200{}
	return &this
}

// NewInlineResponse200WithDefaults instantiates a new InlineResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200WithDefaults() *InlineResponse200 {
	this := InlineResponse200{}
	return &this
}

// GetDeploymentDelayStartTimeSec returns the DeploymentDelayStartTimeSec field value if set, zero value otherwise.
func (o *InlineResponse200) GetDeploymentDelayStartTimeSec() int32 {
	if o == nil || o.DeploymentDelayStartTimeSec == nil {
		var ret int32
		return ret
	}
	return *o.DeploymentDelayStartTimeSec
}

// GetDeploymentDelayStartTimeSecOk returns a tuple with the DeploymentDelayStartTimeSec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetDeploymentDelayStartTimeSecOk() (*int32, bool) {
	if o == nil || o.DeploymentDelayStartTimeSec == nil {
		return nil, false
	}
	return o.DeploymentDelayStartTimeSec, true
}

// HasDeploymentDelayStartTimeSec returns a boolean if a field has been set.
func (o *InlineResponse200) HasDeploymentDelayStartTimeSec() bool {
	if o != nil && o.DeploymentDelayStartTimeSec != nil {
		return true
	}

	return false
}

// SetDeploymentDelayStartTimeSec gets a reference to the given int32 and assigns it to the DeploymentDelayStartTimeSec field.
func (o *InlineResponse200) SetDeploymentDelayStartTimeSec(v int32) {
	o.DeploymentDelayStartTimeSec = &v
}

// GetBuildTimeoutMaxSec returns the BuildTimeoutMaxSec field value if set, zero value otherwise.
func (o *InlineResponse200) GetBuildTimeoutMaxSec() int32 {
	if o == nil || o.BuildTimeoutMaxSec == nil {
		var ret int32
		return ret
	}
	return *o.BuildTimeoutMaxSec
}

// GetBuildTimeoutMaxSecOk returns a tuple with the BuildTimeoutMaxSec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetBuildTimeoutMaxSecOk() (*int32, bool) {
	if o == nil || o.BuildTimeoutMaxSec == nil {
		return nil, false
	}
	return o.BuildTimeoutMaxSec, true
}

// HasBuildTimeoutMaxSec returns a boolean if a field has been set.
func (o *InlineResponse200) HasBuildTimeoutMaxSec() bool {
	if o != nil && o.BuildTimeoutMaxSec != nil {
		return true
	}

	return false
}

// SetBuildTimeoutMaxSec gets a reference to the given int32 and assigns it to the BuildTimeoutMaxSec field.
func (o *InlineResponse200) SetBuildTimeoutMaxSec(v int32) {
	o.BuildTimeoutMaxSec = &v
}

func (o InlineResponse200) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DeploymentDelayStartTimeSec != nil {
		toSerialize["deployment.delay_start_time_sec"] = o.DeploymentDelayStartTimeSec
	}
	if o.BuildTimeoutMaxSec != nil {
		toSerialize["build.timeout_max_sec"] = o.BuildTimeoutMaxSec
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200 struct {
	value *InlineResponse200
	isSet bool
}

func (v NullableInlineResponse200) Get() *InlineResponse200 {
	return v.value
}

func (v *NullableInlineResponse200) Set(val *InlineResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200(val *InlineResponse200) *NullableInlineResponse200 {
	return &NullableInlineResponse200{value: val, isSet: true}
}

func (v NullableInlineResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
