/*
Qovery API

- Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.

API version: 1.0.4
Contact: support+api+documentation@qovery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery

import (
	"encoding/json"
	"fmt"
)

// checks if the ClusterFeatureNatGatewayTypeGcp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterFeatureNatGatewayTypeGcp{}

// ClusterFeatureNatGatewayTypeGcp struct for ClusterFeatureNatGatewayTypeGcp
type ClusterFeatureNatGatewayTypeGcp struct {
	Provider         string `json:"provider"`
	StaticIpsEnabled bool   `json:"static_ips_enabled"`
	// Number of static IPs to allocate. Must be >= 1 when static_ips_enabled is true.
	StaticIpsCount       int32 `json:"static_ips_count"`
	AdditionalProperties map[string]interface{}
}

type _ClusterFeatureNatGatewayTypeGcp ClusterFeatureNatGatewayTypeGcp

// NewClusterFeatureNatGatewayTypeGcp instantiates a new ClusterFeatureNatGatewayTypeGcp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterFeatureNatGatewayTypeGcp(provider string, staticIpsEnabled bool, staticIpsCount int32) *ClusterFeatureNatGatewayTypeGcp {
	this := ClusterFeatureNatGatewayTypeGcp{}
	this.Provider = provider
	this.StaticIpsEnabled = staticIpsEnabled
	this.StaticIpsCount = staticIpsCount
	return &this
}

// NewClusterFeatureNatGatewayTypeGcpWithDefaults instantiates a new ClusterFeatureNatGatewayTypeGcp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterFeatureNatGatewayTypeGcpWithDefaults() *ClusterFeatureNatGatewayTypeGcp {
	this := ClusterFeatureNatGatewayTypeGcp{}
	return &this
}

// GetProvider returns the Provider field value
func (o *ClusterFeatureNatGatewayTypeGcp) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *ClusterFeatureNatGatewayTypeGcp) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *ClusterFeatureNatGatewayTypeGcp) SetProvider(v string) {
	o.Provider = v
}

// GetStaticIpsEnabled returns the StaticIpsEnabled field value
func (o *ClusterFeatureNatGatewayTypeGcp) GetStaticIpsEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.StaticIpsEnabled
}

// GetStaticIpsEnabledOk returns a tuple with the StaticIpsEnabled field value
// and a boolean to check if the value has been set.
func (o *ClusterFeatureNatGatewayTypeGcp) GetStaticIpsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StaticIpsEnabled, true
}

// SetStaticIpsEnabled sets field value
func (o *ClusterFeatureNatGatewayTypeGcp) SetStaticIpsEnabled(v bool) {
	o.StaticIpsEnabled = v
}

// GetStaticIpsCount returns the StaticIpsCount field value
func (o *ClusterFeatureNatGatewayTypeGcp) GetStaticIpsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StaticIpsCount
}

// GetStaticIpsCountOk returns a tuple with the StaticIpsCount field value
// and a boolean to check if the value has been set.
func (o *ClusterFeatureNatGatewayTypeGcp) GetStaticIpsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StaticIpsCount, true
}

// SetStaticIpsCount sets field value
func (o *ClusterFeatureNatGatewayTypeGcp) SetStaticIpsCount(v int32) {
	o.StaticIpsCount = v
}

func (o ClusterFeatureNatGatewayTypeGcp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterFeatureNatGatewayTypeGcp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	toSerialize["static_ips_enabled"] = o.StaticIpsEnabled
	toSerialize["static_ips_count"] = o.StaticIpsCount

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterFeatureNatGatewayTypeGcp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
		"static_ips_enabled",
		"static_ips_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterFeatureNatGatewayTypeGcp := _ClusterFeatureNatGatewayTypeGcp{}

	err = json.Unmarshal(data, &varClusterFeatureNatGatewayTypeGcp)

	if err != nil {
		return err
	}

	*o = ClusterFeatureNatGatewayTypeGcp(varClusterFeatureNatGatewayTypeGcp)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "provider")
		delete(additionalProperties, "static_ips_enabled")
		delete(additionalProperties, "static_ips_count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterFeatureNatGatewayTypeGcp struct {
	value *ClusterFeatureNatGatewayTypeGcp
	isSet bool
}

func (v NullableClusterFeatureNatGatewayTypeGcp) Get() *ClusterFeatureNatGatewayTypeGcp {
	return v.value
}

func (v *NullableClusterFeatureNatGatewayTypeGcp) Set(val *ClusterFeatureNatGatewayTypeGcp) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterFeatureNatGatewayTypeGcp) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterFeatureNatGatewayTypeGcp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterFeatureNatGatewayTypeGcp(val *ClusterFeatureNatGatewayTypeGcp) *NullableClusterFeatureNatGatewayTypeGcp {
	return &NullableClusterFeatureNatGatewayTypeGcp{value: val, isSet: true}
}

func (v NullableClusterFeatureNatGatewayTypeGcp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterFeatureNatGatewayTypeGcp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
