/*
Qovery API

- Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.

API version: 1.0.4
Contact: support+api+documentation@qovery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery

import (
	"encoding/json"
	"fmt"
)

// checks if the SecretManagerAccessRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretManagerAccessRequest{}

// SecretManagerAccessRequest struct for SecretManagerAccessRequest
type SecretManagerAccessRequest struct {
	Id                   NullableString                        `json:"id,omitempty"`
	Name                 string                                `json:"name"`
	Endpoint             SecretManagerEndpointConfigurationDto `json:"endpoint"`
	Authentication       SecretManagerAuthenticationDto        `json:"authentication"`
	AdditionalProperties map[string]interface{}
}

type _SecretManagerAccessRequest SecretManagerAccessRequest

// NewSecretManagerAccessRequest instantiates a new SecretManagerAccessRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretManagerAccessRequest(name string, endpoint SecretManagerEndpointConfigurationDto, authentication SecretManagerAuthenticationDto) *SecretManagerAccessRequest {
	this := SecretManagerAccessRequest{}
	this.Name = name
	this.Endpoint = endpoint
	this.Authentication = authentication
	return &this
}

// NewSecretManagerAccessRequestWithDefaults instantiates a new SecretManagerAccessRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretManagerAccessRequestWithDefaults() *SecretManagerAccessRequest {
	this := SecretManagerAccessRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SecretManagerAccessRequest) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SecretManagerAccessRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *SecretManagerAccessRequest) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *SecretManagerAccessRequest) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *SecretManagerAccessRequest) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *SecretManagerAccessRequest) UnsetId() {
	o.Id.Unset()
}

// GetName returns the Name field value
func (o *SecretManagerAccessRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SecretManagerAccessRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SecretManagerAccessRequest) SetName(v string) {
	o.Name = v
}

// GetEndpoint returns the Endpoint field value
func (o *SecretManagerAccessRequest) GetEndpoint() SecretManagerEndpointConfigurationDto {
	if o == nil {
		var ret SecretManagerEndpointConfigurationDto
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *SecretManagerAccessRequest) GetEndpointOk() (*SecretManagerEndpointConfigurationDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *SecretManagerAccessRequest) SetEndpoint(v SecretManagerEndpointConfigurationDto) {
	o.Endpoint = v
}

// GetAuthentication returns the Authentication field value
func (o *SecretManagerAccessRequest) GetAuthentication() SecretManagerAuthenticationDto {
	if o == nil {
		var ret SecretManagerAuthenticationDto
		return ret
	}

	return o.Authentication
}

// GetAuthenticationOk returns a tuple with the Authentication field value
// and a boolean to check if the value has been set.
func (o *SecretManagerAccessRequest) GetAuthenticationOk() (*SecretManagerAuthenticationDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authentication, true
}

// SetAuthentication sets field value
func (o *SecretManagerAccessRequest) SetAuthentication(v SecretManagerAuthenticationDto) {
	o.Authentication = v
}

func (o SecretManagerAccessRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretManagerAccessRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	toSerialize["name"] = o.Name
	toSerialize["endpoint"] = o.Endpoint
	toSerialize["authentication"] = o.Authentication

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecretManagerAccessRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"endpoint",
		"authentication",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretManagerAccessRequest := _SecretManagerAccessRequest{}

	err = json.Unmarshal(data, &varSecretManagerAccessRequest)

	if err != nil {
		return err
	}

	*o = SecretManagerAccessRequest(varSecretManagerAccessRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "endpoint")
		delete(additionalProperties, "authentication")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecretManagerAccessRequest struct {
	value *SecretManagerAccessRequest
	isSet bool
}

func (v NullableSecretManagerAccessRequest) Get() *SecretManagerAccessRequest {
	return v.value
}

func (v *NullableSecretManagerAccessRequest) Set(val *SecretManagerAccessRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretManagerAccessRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretManagerAccessRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretManagerAccessRequest(val *SecretManagerAccessRequest) *NullableSecretManagerAccessRequest {
	return &NullableSecretManagerAccessRequest{value: val, isSet: true}
}

func (v NullableSecretManagerAccessRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretManagerAccessRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
