/*
Qovery API

- Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.

API version: 1.0.3
Contact: support+api+documentation@qovery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qovery

import (
	"encoding/json"
)

// checks if the TerraformFilesSourceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerraformFilesSourceRequest{}

// TerraformFilesSourceRequest struct for TerraformFilesSourceRequest
type TerraformFilesSourceRequest struct {
	Id                   *string `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TerraformFilesSourceRequest TerraformFilesSourceRequest

// NewTerraformFilesSourceRequest instantiates a new TerraformFilesSourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerraformFilesSourceRequest() *TerraformFilesSourceRequest {
	this := TerraformFilesSourceRequest{}
	return &this
}

// NewTerraformFilesSourceRequestWithDefaults instantiates a new TerraformFilesSourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerraformFilesSourceRequestWithDefaults() *TerraformFilesSourceRequest {
	this := TerraformFilesSourceRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TerraformFilesSourceRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerraformFilesSourceRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TerraformFilesSourceRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TerraformFilesSourceRequest) SetId(v string) {
	o.Id = &v
}

func (o TerraformFilesSourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerraformFilesSourceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TerraformFilesSourceRequest) UnmarshalJSON(data []byte) (err error) {
	varTerraformFilesSourceRequest := _TerraformFilesSourceRequest{}

	err = json.Unmarshal(data, &varTerraformFilesSourceRequest)

	if err != nil {
		return err
	}

	*o = TerraformFilesSourceRequest(varTerraformFilesSourceRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTerraformFilesSourceRequest struct {
	value *TerraformFilesSourceRequest
	isSet bool
}

func (v NullableTerraformFilesSourceRequest) Get() *TerraformFilesSourceRequest {
	return v.value
}

func (v *NullableTerraformFilesSourceRequest) Set(val *TerraformFilesSourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTerraformFilesSourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTerraformFilesSourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerraformFilesSourceRequest(val *TerraformFilesSourceRequest) *NullableTerraformFilesSourceRequest {
	return &NullableTerraformFilesSourceRequest{value: val, isSet: true}
}

func (v NullableTerraformFilesSourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerraformFilesSourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
